### ISSUE TITLE
LCH colors?

### ISSUE THREAD

**Issue by carlmjohnson** [chipcullen/colorosetta#4]
Very cool project. Any possibility of adding LCH support? (See http://lea.verou.me/2020/04/lch-colors-in-css-what-why-and-how/ and https://css.land/lch/) LCH is better than HSL at shifting a color into darker and lighter versions, but the css.land LCH picker only spits out RGBA() values. Having hex values and an LCH picker in one place would be very useful.

**Comment by chipcullen** [comment]
@carlmjohnson sorry I never responded to this issue that you raised - I did add LCH support last year:

https://github.com/chipcullen/colorosetta/commit/80ed8ac442452ddc4bfefe5f039d8b7f67e48395

It's also part of the VS code extension that I made: https://marketplace.visualstudio.com/items?itemName=chipcullen.colorosetta
